# Generated by Django 5.2.15 on 2026-06-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchases_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
